export interface Country {
  countryCode: string
  countryNameCN: string
  countryNameEN: string
  countryDialingCode: string
}

// countryCode.countries
export const countries: Country[] = [
  { countryCode: 'CN', countryNameCN: '中国', countryNameEN: 'China', countryDialingCode: '86' },
  { countryCode: 'JP', countryNameCN: '日本', countryNameEN: 'Japan', countryDialingCode: '81' },
  { countryCode: 'KR', countryNameCN: '韩国', countryNameEN: 'Korea', countryDialingCode: '82' },
  { countryCode: 'PH', countryNameCN: '菲律宾', countryNameEN: 'Philippines', countryDialingCode: '63' },
  { countryCode: 'KH', countryNameCN: '柬埔寨', countryNameEN: 'Cambodia', countryDialingCode: '855' },
  { countryCode: 'VN', countryNameCN: '越南', countryNameEN: 'Viet Nam', countryDialingCode: '84' },
  { countryCode: 'TH', countryNameCN: '泰国', countryNameEN: 'Thailand', countryDialingCode: '66' },
  { countryCode: 'ID', countryNameCN: '印度尼西亚', countryNameEN: 'Indonesia', countryDialingCode: '62' },
  { countryCode: 'MY', countryNameCN: '马来西亚', countryNameEN: 'Malaysia', countryDialingCode: '60' },
  { countryCode: 'SG', countryNameCN: '新加坡', countryNameEN: 'Singapore', countryDialingCode: '65' },
  { countryCode: 'MM', countryNameCN: '缅甸', countryNameEN: 'Myanmar', countryDialingCode: '95' },
  { countryCode: 'LA', countryNameCN: '老挝', countryNameEN: 'Lao PDR', countryDialingCode: '856' },
  { countryCode: 'BN', countryNameCN: '汶莱', countryNameEN: 'Brunei Darussalam', countryDialingCode: '673' },
  { countryCode: 'ES', countryNameCN: '西班牙', countryNameEN: 'Spain', countryDialingCode: '34' },
  { countryCode: 'BR', countryNameCN: '巴西', countryNameEN: 'Brazil', countryDialingCode: '55' },
  { countryCode: 'TR', countryNameCN: '土耳其', countryNameEN: 'Turkey', countryDialingCode: '90' },
  { countryCode: 'BD', countryNameCN: '孟加拉', countryNameEN: 'Bangladesh', countryDialingCode: '880' },
  { countryCode: 'HK', countryNameCN: '香港', countryNameEN: 'Hong Kong', countryDialingCode: '852' },
  { countryCode: 'MO', countryNameCN: '澳门', countryNameEN: 'Macau', countryDialingCode: '853' },
  { countryCode: 'TW', countryNameCN: '台湾', countryNameEN: 'Taiwan', countryDialingCode: '886' },
  { countryCode: 'IN', countryNameCN: '印度', countryNameEN: 'India', countryDialingCode: '91' },
  { countryCode: 'GB', countryNameCN: '英国', countryNameEN: 'United Kingdom', countryDialingCode: '44' },
  { countryCode: 'CA', countryNameCN: '加拿大', countryNameEN: 'Canada', countryDialingCode: '1' },
  { countryCode: 'US', countryNameCN: '美国', countryNameEN: 'America', countryDialingCode: '1' },
  { countryCode: 'AU', countryNameCN: '澳大利亚', countryNameEN: 'Australia', countryDialingCode: '61' },
  { countryCode: 'NZ', countryNameCN: '新西兰', countryNameEN: 'New Zealand', countryDialingCode: '64' },
  { countryCode: 'NP', countryNameCN: '尼泊尔', countryNameEN: 'Nepal', countryDialingCode: '977' },
  { countryCode: 'CO', countryNameCN: '哥伦比亚', countryNameEN: 'Colombia', countryDialingCode: '57' },
  { countryCode: 'PE', countryNameCN: '秘鲁', countryNameEN: 'Peru', countryDialingCode: '51' },
  { countryCode: 'IT', countryNameCN: '意大利', countryNameEN: 'Italy', countryDialingCode: '39' },
  { countryCode: 'FR', countryNameCN: '法国', countryNameEN: 'France', countryDialingCode: '33' },
  { countryCode: 'TLG', countryNameCN: '天龙国', countryNameEN: 'TLG', countryDialingCode: '63' },
  { countryCode: 'PK', countryNameCN: '巴基斯坦', countryNameEN: 'Pakistan', countryDialingCode: '92' },
  { countryCode: 'MN', countryNameCN: '蒙古', countryNameEN: 'Mongolia', countryDialingCode: '976' },
  { countryCode: 'NG', countryNameCN: '尼日利亚', countryNameEN: 'Nigeria', countryDialingCode: '234' },
  { countryCode: 'SA', countryNameCN: '沙特阿拉伯', countryNameEN: 'Saudi Arabia', countryDialingCode: '966' },
  { countryCode: 'DE', countryNameCN: '德国', countryNameEN: 'Germany', countryDialingCode: '49' },
  { countryCode: 'BH', countryNameCN: '巴林', countryNameEN: 'Bahrain', countryDialingCode: '973' },
  { countryCode: 'KW', countryNameCN: '科威特', countryNameEN: 'Kuwait', countryDialingCode: '965' },
  { countryCode: 'NL', countryNameCN: '荷兰', countryNameEN: 'Netherlands', countryDialingCode: '31' },
  { countryCode: 'AO', countryNameCN: '安哥拉', countryNameEN: 'Angola', countryDialingCode: '244' },
  { countryCode: 'AE', countryNameCN: '阿联酋', countryNameEN: 'United Arab Emirates', countryDialingCode: '971' },
  { countryCode: 'MX', countryNameCN: '墨西哥', countryNameEN: 'Mexico', countryDialingCode: '52' },
  { countryCode: 'CC', countryNameCN: '埃及', countryNameEN: 'Egypt', countryDialingCode: '20' },
  { countryCode: 'IR', countryNameCN: '伊朗', countryNameEN: 'Iran', countryDialingCode: '98' },
  { countryCode: 'AF', countryNameCN: '阿富汗', countryNameEN: 'Afghanistan', countryDialingCode: '93' },
  { countryCode: 'TJ', countryNameCN: '塔吉克斯坦', countryNameEN: 'Tajikistan', countryDialingCode: '992' },
  { countryCode: 'RU', countryNameCN: '俄罗斯', countryNameEN: 'Russia', countryDialingCode: '7' },
  { countryCode: 'BY', countryNameCN: '白俄罗斯', countryNameEN: 'Belarus', countryDialingCode: '375' },
  { countryCode: 'KG', countryNameCN: '吉尔吉斯', countryNameEN: 'Kyrgyzstan', countryDialingCode: '996' },
  { countryCode: 'KZ', countryNameCN: '哈萨克', countryNameEN: 'Kazakhstan', countryDialingCode: '7' },
  { countryCode: 'UZ', countryNameCN: '乌兹别克', countryNameEN: 'Uzbekistan', countryDialingCode: '998' },
  { countryCode: 'KE', countryNameCN: '肯尼亚', countryNameEN: 'Kenya', countryDialingCode: '254' },
  { countryCode: 'GT', countryNameCN: '危地马拉', countryNameEN: 'Guatemala', countryDialingCode: '502' },
  { countryCode: 'HN', countryNameCN: '洪都拉斯', countryNameEN: 'Honduras', countryDialingCode: '504' },
  { countryCode: 'NI', countryNameCN: '尼加拉瓜', countryNameEN: 'Nicaragua', countryDialingCode: '505' },
  { countryCode: 'CI', countryNameCN: '科特迪瓦', countryNameEN: 'Côte d\'Ivoire', countryDialingCode: '225' },
  { countryCode: 'CL', countryNameCN: '智利', countryNameEN: 'chile', countryDialingCode: '56' },
  { countryCode: 'BEN', countryNameCN: '贝宁共和国', countryNameEN: 'Benin', countryDialingCode: '229' },
  { countryCode: 'BF', countryNameCN: '布基纳法索', countryNameEN: 'Burkina Faso', countryDialingCode: '226' },
  { countryCode: 'GNB', countryNameCN: '几内亚比绍共和国', countryNameEN: 'Guiné-Bissau', countryDialingCode: '245' },
  { countryCode: 'MLI', countryNameCN: '马里', countryNameEN: 'République du Mali', countryDialingCode: '223' },
  { countryCode: 'NE', countryNameCN: '尼日尔共和国', countryNameEN: 'Niger', countryDialingCode: '227' },
  { countryCode: 'SEN', countryNameCN: '塞内加尔', countryNameEN: 'Sénégal', countryDialingCode: '221' },
  { countryCode: 'TGO', countryNameCN: '多哥共和国', countryNameEN: 'Togo', countryDialingCode: '228' },
  { countryCode: 'GH', countryNameCN: '加纳共和国', countryNameEN: 'Republic of Ghana', countryDialingCode: '233' },
]

export default countries
